// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyUfaZHhlxkoH4L-fUgxQ50NhNF65QEV4',
    appId: '1:337747615169:web:23434fe170fbafcab9e340',
    messagingSenderId: '337747615169',
    projectId: 'dr-green-689e5',
    authDomain: 'dr-green-689e5.firebaseapp.com',
    storageBucket: 'dr-green-689e5.appspot.com',
    measurementId: 'G-Y0VJLNGG45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkoUsKz7RavhxeHXmgAzc3yovj2TboRGw',
    appId: '1:337747615169:android:876dddd392b4bddcb9e340',
    messagingSenderId: '337747615169',
    projectId: 'dr-green-689e5',
    storageBucket: 'dr-green-689e5.appspot.com',
  );
}
